# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
    - pandoc
    - python-pip
    - texlive-latex-base

before_script:
  - pip install --user panflute

script:
  - cd docs
  - ../bin/pdsite build

