language: python

addons:
  apt:
    packages:
    - pandoc
    - python3-pip
    - python3-setuptools
    - texlive-latex-base

before_script:
  - pip3 install --user wheel
  - pip3 install --user panflute bs4
  # Make Python 3 the default, so pandoc will use it
  - sudo rm /usr/bin/python
  - sudo ln -s /usr/bin/python3 /usr/bin/python
  - python --version

script:
  - cd docs
  - ../bin/pdsite build

