language: python

addons:
  apt:
    packages:
    - pandoc
    - python3-setuptools
    - texlive-latex-base

before_script:
  - python --version
  - pip install -r requirements.txt

script:
  - cd docs
  - ../bin/pdsite build

