# Use the (faster) container-based infrastructure, see also
# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

addons:
  apt:
    packages:
    - pandoc
    - python3-pip
    - python3-setuptools
    - texlive-latex-base

before_script:
  - pip3 install --user panflute bs4

script:
  - cd docs
  - ../bin/pdsite build

